---
title: "爬蟲練習"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE}
#Load the library
library(xml2)
library(rvest)
library(stringr)
```

```{r}
#Load HTML website:
html <- read_html("https://rate.bot.com.tw/xrt?Lang=zh-TW")

#Structure separate variables according to node
country <- html_nodes(html, ".print_show")
cashbuy <- html_nodes(html, ".phone-small-font+ .text-right")
cashbid <- html_nodes(html, ".print_hide+ .rate-content-cash.text-right")

#Check Length
length(country)
length(cashbuy)
length(cashbid)

```
```{r}
#Define separate variables & Organize
countryvalues<-html_text(country)
 countryvalues<-str_replace_all(countryvalues, "[\r\n]", "")
 countryvalues<-str_replace_all(countryvalues, " ", "")
cashbuyvalues<-html_text(cashbuy)
 temp<-matrix(cashbuyvalues,2,19)
 cashbuyvalues<-temp[1,]
cashbidvalues<-html_text(cashbid)

#Structure data frame and remove heading
df = data.frame(countryvalues, cashbuyvalues, cashbidvalues)
df
```


